CREATE DATABASE systock;
USE systock;

CREATE TABLE endereco (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    cep VARCHAR(9) CHECK(LENGTH(cep)=9) NOT NULL,-- SE FOR CHAR ENTRA COM CARAC-
    -- TER A MENOS, NÃO FAZ O CHECK CORRETAMENTE
    estado VARCHAR(50) NOT NULL,
    complemento VARCHAR(255),
    cidade VARCHAR(50) NOT NULL,
    numero INTEGER CHECK(numero>0) NOT NULL,
    logradouro VARCHAR(200) NOT NULL
);

ALTER TABLE endereco ADD CONSTRAINT pkEndereco PRIMARY KEY(id);

select * from endereco