CREATE TABLE companhia(
    cnpj VARCHAR(14) CHECK(LENGTH(cnpj)=14) NOT NULL, -- SE FOR CHAR ENTRA COM CARAC-
    -- TER A MENOS, NÃO FAZ O CHECK CORRETAMENTE
    nome VARCHAR(50) UNIQUE NOT NULL, 
    email VARCHAR(45) UNIQUE NOT NULL,
    estadoDeRegistro VARCHAR(50) NOT NULL,
    EnderecoId INTEGER NOT NULL
);

ALTER TABLE companhia ADD CONSTRAINT pkCompanhia PRIMARY KEY(id);
ALTER TABLE companhia ADD CONSTRAINT fk_
